spring:
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: ${GOOGLE_CLIENT_ID}
#            clientSecret: ${GOOGLE_CLIENT_SECRET}
#          facebook:
#            clientId: ${FACEBOOK_CLIENT_ID}
#            clientSecret: ${FACEBOOK_CLIENT_SECRET}
#          github:
#            clientId: ${GITHUB_CLIENT_ID}
#            clientSecret: ${GITHUB_CLIENT_SECRET}

#cloudinary:
#  name: ${CLOUD_NAME}
#  api_key: ${CLOUD_API_KEY}
#  api_secret: ${CLOUD_API_SECRET}
#
#app:
#  auth:
#    jwt:
#      secret: ${JWT_SECRET}
#    tokenSecret: ${JWT_TOKEN_SECRET}
#    tokenExpirationMsec: ${JWT_EXPIRATION}
#
#  payment:
#    paypal:
#      clientId: ${PAYPAL_CLIENT_ID}
#      secret: ${PAYPAL_SECRET}
#    vnpay:
#      tmnCode: ${VNPAY_CODE}
#      secret: ${VNPAY_SECRET}
#
#url:
#  client: ${CLIENT_URL}
